info:
  title: Transcribe API
  version: 0.1.0
tags: []
paths:
  /ping:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingOut'
          description: Successful response
      summary: Ping
openapi: 3.0.3
components:
  schemas:
    SocketTranscriptionPayload:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
        text:
          type: string
        translation:
          type: string
        id:
          type: string
    SocketJoinLeavePayload:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
    SocketMessagePayload:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
        text:
          type: string
    SocketInterimTranscriptionPayload:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
        text:
          type: string
        id:
          type: string
    PingOut:
      type: object
      properties:
        socket_transcription_payload:
          $ref: '#/components/schemas/SocketTranscriptionPayload'
        socket_join_leave_payload:
          $ref: '#/components/schemas/SocketJoinLeavePayload'
        socket_message_payload:
          $ref: '#/components/schemas/SocketMessagePayload'
        socket_interim_transcription_payload:
          $ref: '#/components/schemas/SocketInterimTranscriptionPayload'
        message:
          type: string

