info:
  title: Transcribe API
  version: 0.1.0
tags: []
paths:
  /ping:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingOut'
          description: Successful response
      summary: Ping
openapi: 3.0.3
components:
  schemas:
    FinalTranscription:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
        text:
          type: string
        translation:
          type: string
        id:
          type: string
    JoinLeaveMessage:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
    Message:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
        text:
          type: string
    InterimTranscription:
      type: object
      properties:
        username:
          type: string
        room:
          type: string
        text:
          type: string
        id:
          type: string
    SocketResources:
      type: object
      properties:
        socket_transcription_payload:
          $ref: '#/components/schemas/FinalTranscription'
        socket_join_leave_payload:
          $ref: '#/components/schemas/JoinLeaveMessage'
        socket_message_payload:
          $ref: '#/components/schemas/Message'
        socket_interim_transcription_payload:
          $ref: '#/components/schemas/InterimTranscription'
    PingOut:
      type: object
      properties:
        socket_resources:
          $ref: '#/components/schemas/SocketResources'
        message:
          type: string

